doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

        types:
            utc_datetime_microseconds_immutable: ProjectManagement\Shared\Infrastructure\Domain\DoctrineExtensions\Dbal\Types\UtcDateTimeMicrosecondsImmutableType

            release_publication_id: ProjectManagement\ReleasePublication\Infrastructure\Domain\DoctrineExtensions\Dbal\Types\ReleasePublicationIdType
            release_branch_name: ProjectManagement\ReleasePublication\Infrastructure\Domain\DoctrineExtensions\Dbal\Types\ReleaseBranchNameType
            release_publication_status: ProjectManagement\ReleasePublication\Infrastructure\Domain\DoctrineExtensions\Dbal\Types\StatusType
            
            issue_list: ProjectManagement\Shared\Infrastructure\Domain\DoctrineExtensions\Dbal\Types\IssueListType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            ReleasePublication:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/ReleasePublication/Infrastructure/config/doctrine'
                prefix: ProjectManagement\ReleasePublication\Domain\Model
                alias: ReleasePublication
        controller_resolver:
            auto_mapping: true

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
