# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    eight_points_guzzle.symfony_log_formatter.pattern: '{method} {uri} {code} {res_headers} {res_body}'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            Psr\Http\Message\UriInterface $jiraUrl: '@release_management.jira_url'
            ProjectManagement\Shared\Domain\Model\ContinuousIntegration\Project\ProjectId $backendProjectId: '@release_management.gitlab_project.backend'
            ProjectManagement\Shared\Domain\Model\ContinuousIntegration\Project\ProjectId $frontendProjectId: '@release_management.gitlab_project.frontend'
            ProjectManagement\Shared\Domain\Model\SourceCodeRepository\SourceCodeRepositoryInterface $backendSourceCodeRepository: '@release_management.gitlab_backend_client'
            ProjectManagement\Shared\Domain\Model\SourceCodeRepository\SourceCodeRepositoryInterface $frontendSourceCodeRepository: '@release_management.gitlab_frontend_client'
            ProjectManagement\Shared\Domain\Model\ContinuousIntegration\ContinuousIntegrationClientInterface $frontendCiClient: '@release_management.gitlab_frontend_client'
            ProjectManagement\Shared\Domain\Model\ContinuousIntegration\ContinuousIntegrationClientInterface $backendCiClient: '@release_management.gitlab_backend_client'
    _instanceof:
        # services whose classes are instances of CustomInterface will be tagged automatically
        ProjectManagement\Shared\Domain\Model\DevelopmentCollaboration\MergeRequestManagerInterface:
            tags: ['release_management.development_collaboration.merge_request_manager']



    Invis1ble\Messenger\Command\CommandBus:
        arguments: ['@messenger.bus.command.async']

    

    application_layer:
        namespace: ProjectManagement\
        resource: '../src/*/Application/**/*{Handler}.php'

    ui_layer:
        namespace: ProjectManagement\
        resource: '../src/*/Ui/**/*{Command}.php'

    infrastructure_layer:
        namespace: ProjectManagement\
        resource: '../src/*/Infrastructure/**/*{Bus,Handler,Factory,Repository,Resolver}.php'
    
    
    
    release_management.jira_url:
        class: Psr\Http\Message\UriInterface
        factory: ['@Psr\Http\Message\UriFactoryInterface', 'createUri']
        arguments: ['%env(JIRA_URL)%']
    
    release_management.gitlab_project.backend:
        class: ProjectManagement\Shared\Domain\Model\ContinuousIntegration\Project\ProjectId
        arguments:
            $value: '%env(GITLAB_BACKEND_PROJECT_ID)%'

    release_management.gitlab_project.frontend:
        class: ProjectManagement\Shared\Domain\Model\ContinuousIntegration\Project\ProjectId
        arguments:
            $value: '%env(GITLAB_FRONTEND_PROJECT_ID)%'
    
    ProjectManagement\Shared\Domain\Model\TaskTracker\Project\Key:
        arguments:
            $value: '%env(JIRA_PROJECT_KEY)%'
    
    ProjectManagement\Shared\Domain\Model\TaskTracker\Board\BoardId:
        arguments:
            $value: '%env(JIRA_SPRINT_BOARD_ID)%'



    
    release_management.gitlab_backend_client:
        class: ProjectManagement\Shared\Infrastructure\Domain\Model\Gitlab\GitlabClient
        arguments:
            $httpClient: '@eight_points_guzzle.client.gitlab'
            $projectId: '@release_management.gitlab_project.backend'
    
    release_management.gitlab_frontend_client:
        class: ProjectManagement\Shared\Infrastructure\Domain\Model\Gitlab\GitlabClient
        arguments:
            $httpClient: '@eight_points_guzzle.client.gitlab'
            $projectId: '@release_management.gitlab_project.frontend'
    
    ProjectManagement\Shared\Infrastructure\Domain\Model\TaskTracker\TaskTracker:
        arguments:
            $httpClient: '@eight_points_guzzle.client.jira'
            $sprintFieldId: '%env(JIRA_SPRINT_SECTION_FIELD_ID)%'
    
    ProjectManagement\HotfixPublication\Infrastructure\Domain\Model\TaskTracker\TaskTracker:
        parent: ProjectManagement\Shared\Infrastructure\Domain\Model\TaskTracker\TaskTracker
    
    ProjectManagement\ReleasePublication\Infrastructure\Domain\Model\TaskTracker\TaskTracker:
        parent: ProjectManagement\Shared\Infrastructure\Domain\Model\TaskTracker\TaskTracker
    
    ProjectManagement\Shared\Infrastructure\Domain\Model\DevelopmentCollaboration\MergeRequest\MergeRequestManagerStack:
        arguments:
            - !tagged_iterator release_management.development_collaboration.merge_request_manager




    GuzzleHttp\Psr7\HttpFactory: ~
    Psr\Http\Message\UriFactoryInterface: '@GuzzleHttp\Psr7\HttpFactory'
    Psr\Http\Message\RequestFactoryInterface: '@GuzzleHttp\Psr7\HttpFactory'
    Psr\Http\Message\StreamFactoryInterface: '@GuzzleHttp\Psr7\HttpFactory'
    
    

    
    ProjectManagement\Shared\Domain\Model\DevelopmentCollaboration\MergeRequest\Details\Status\StatusFactoryInterface: '@ProjectManagement\Shared\Infrastructure\Domain\Model\DevelopmentCollaboration\MergeRequest\Details\Status\StatusFactory'
    ProjectManagement\Shared\Domain\Model\DevelopmentCollaboration\MergeRequest\Details\DetailsFactoryInterface: '@ProjectManagement\Shared\Infrastructure\Domain\Model\DevelopmentCollaboration\MergeRequest\Details\DetailsFactory'
    ProjectManagement\Shared\Domain\Model\TaskTracker\Issue\IssueFactoryInterface: '@ProjectManagement\Shared\Infrastructure\Domain\Model\TaskTracker\Issue\IssueFactory'
    ProjectManagement\HotfixPublication\Domain\Model\HotfixPublicationFactoryInterface: '@ProjectManagement\HotfixPublication\Infrastructure\Domain\Model\HotfixPublicationFactory'
    ProjectManagement\HotfixPublication\Domain\Repository\HotfixPublicationRepositoryInterface: '@ProjectManagement\HotfixPublication\Infrastructure\Domain\Repository\HotfixPublicationRepository'
    ProjectManagement\HotfixPublication\Domain\Model\TaskTracker\TaskTrackerInterface: '@ProjectManagement\HotfixPublication\Infrastructure\Domain\Model\TaskTracker\TaskTracker'
    ProjectManagement\ReleasePublication\Domain\Model\ReleasePublicationFactoryInterface: '@ProjectManagement\ReleasePublication\Infrastructure\Domain\Model\ReleasePublicationFactory'
    ProjectManagement\Shared\Domain\Model\DevelopmentCollaboration\MergeRequest\MergeRequestFactoryInterface: '@ProjectManagement\Shared\Infrastructure\Model\DevelopmentCollaboration\MergeRequestFactory'
    ProjectManagement\Shared\Domain\Model\TaskTracker\Sprint\SprintFactoryInterface: '@ProjectManagement\Shared\Infrastructure\Domain\Model\TaskTracker\Sprint\SprintFactory'
    ProjectManagement\ReleasePublication\Domain\Repository\ReleasePublicationRepositoryInterface: '@ProjectManagement\ReleasePublication\Infrastructure\Domain\Repository\ReleasePublicationRepository'
    ProjectManagement\Shared\Domain\Model\TaskTracker\TaskTrackerInterface: '@ProjectManagement\Shared\Infrastructure\Domain\Model\TaskTracker\TaskTracker'
    ProjectManagement\ReleasePublication\Domain\Model\TaskTracker\TaskTrackerInterface: '@ProjectManagement\ReleasePublication\Infrastructure\Domain\Model\TaskTracker\TaskTracker'
    ProjectManagement\Shared\Domain\Model\TaskTracker\Issue\GuiUrlFactoryInterface: '@ProjectManagement\Shared\Infrastructure\Domain\Model\TaskTracker\Issue\GuiUrlFactory'
    ProjectManagement\Shared\Domain\Model\DevelopmentCollaboration\MergeRequestManagerInterface: '@ProjectManagement\Shared\Infrastructure\Domain\Model\DevelopmentCollaboration\MergeRequest\MergeRequestManagerStack'
    ProjectManagement\Shared\Domain\Model\SourceCodeRepository\NewCommit\SetFrontendApplicationBranchNameCommitFactoryInterface: '@ProjectManagement\Shared\Infrastructure\Domain\Model\SourceCodeRepository\NewCommit\SetFrontendApplicationBranchNameCommitFactory'
