# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    eight_points_guzzle.symfony_log_formatter.pattern: '{method} {uri} {code} {res_headers} {res_body}'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            Psr\Http\Message\UriInterface $jiraUrl: '@release_management.jira_url'
            Invis1ble\ProjectManagement\Shared\Domain\Model\ContinuousIntegration\Project\ProjectId $backendProjectId: '@release_management.gitlab_project.backend'
            Invis1ble\ProjectManagement\Shared\Domain\Model\ContinuousIntegration\Project\ProjectId $frontendProjectId: '@release_management.gitlab_project.frontend'
            Invis1ble\ProjectManagement\Shared\Domain\Model\SourceCodeRepository\SourceCodeRepositoryInterface $backendSourceCodeRepository: '@release_management.gitlab_backend_client'
            Invis1ble\ProjectManagement\Shared\Domain\Model\SourceCodeRepository\SourceCodeRepositoryInterface $frontendSourceCodeRepository: '@release_management.gitlab_frontend_client'
            Invis1ble\ProjectManagement\Shared\Domain\Model\ContinuousIntegration\ContinuousIntegrationClientInterface $frontendCiClient: '@release_management.gitlab_frontend_client'
            Invis1ble\ProjectManagement\Shared\Domain\Model\ContinuousIntegration\ContinuousIntegrationClientInterface $backendCiClient: '@release_management.gitlab_backend_client'
    _instanceof:
        # services whose classes are instances of CustomInterface will be tagged automatically
        Invis1ble\ProjectManagement\Shared\Domain\Model\DevelopmentCollaboration\MergeRequest\MergeRequestManagerInterface:
            tags: ['release_management.development_collaboration.merge_request_manager']





    serializer.normalizer.property:
        class: Symfony\Component\Serializer\Normalizer\PropertyNormalizer
        tags:
            - { name: serializer.normalizer, priority: -930 }

    invis1ble_project_management.normalizer.string:
        class: Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Serializer\StringNormalizer
        tags:
            - { name: serializer.normalizer, priority: 10 }

    invis1ble_project_management.normalizer.uid:
        class: Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Serializer\UidNormalizer
        arguments: ['@serializer.normalizer.uid']
        tags:
            - { name: serializer.normalizer, priority: 10 }

    invis1ble_project_management.normalizer.id:
        class: Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Serializer\IdNormalizer
        tags:
            - { name: serializer.normalizer, priority: 10 }

    Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Serializer\ListNormalizer:
        tags:
            - { name: serializer.normalizer, priority: 10 }

    Invis1ble\ProjectManagement\HotfixPublication\Infrastructure\Domain\Model\Status\StatusNormalizer:
        tags:
            - { name: serializer.normalizer, priority: 990 }

    Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Model\DevelopmentCollaboration\MergeRequest\Details\Status\StatusNormalizer:
        tags:
            - { name: serializer.normalizer, priority: 990 }





    Invis1ble\Messenger\Command\CommandBus:
        arguments: ['@messenger.bus.command.async']    
    
    
    
    domain_layer:
        namespace: Invis1ble\ProjectManagement\
        resource: '../src/*/Domain/**/*{Factory}.php'

    application_layer:
        namespace: Invis1ble\ProjectManagement\
        resource: '../src/*/Application/**/*{Handler}.php'

    ui_layer:
        namespace: Invis1ble\ProjectManagement\
        resource: '../src/*/Ui/**/*{Command}.php'

    infrastructure_layer:
        namespace: Invis1ble\ProjectManagement\
        resource: '../src/*/Infrastructure/**/*{Bus,Handler,Factory,Repository,Resolver}.php'
    
    
    
    release_management.jira_url:
        class: Psr\Http\Message\UriInterface
        factory: ['@Psr\Http\Message\UriFactoryInterface', 'createUri']
        arguments: ['%env(JIRA_URL)%']
    
    release_management.gitlab_project.backend:
        class: Invis1ble\ProjectManagement\Shared\Domain\Model\ContinuousIntegration\Project\ProjectId
        arguments:
            $value: '%env(GITLAB_BACKEND_PROJECT_ID)%'

    release_management.gitlab_project.frontend:
        class: Invis1ble\ProjectManagement\Shared\Domain\Model\ContinuousIntegration\Project\ProjectId
        arguments:
            $value: '%env(GITLAB_FRONTEND_PROJECT_ID)%'
    
    Invis1ble\ProjectManagement\Shared\Domain\Model\TaskTracker\Project\Key:
        arguments:
            $value: '%env(JIRA_PROJECT_KEY)%'
    
    Invis1ble\ProjectManagement\Shared\Domain\Model\TaskTracker\Board\BoardId:
        arguments:
            $value: '%env(JIRA_SPRINT_BOARD_ID)%'



    
    release_management.gitlab_backend_client:
        class: Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Model\ContinuousIntegration\Gitlab\GitlabClient
        arguments:
            $httpClient: '@eight_points_guzzle.client.gitlab'
            $projectId: '@release_management.gitlab_project.backend'
    
    release_management.gitlab_frontend_client:
        class: Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Model\ContinuousIntegration\Gitlab\GitlabClient
        arguments:
            $httpClient: '@eight_points_guzzle.client.gitlab'
            $projectId: '@release_management.gitlab_project.frontend'
    
    Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Model\TaskTracker\TaskTracker:
        arguments:
            $httpClient: '@eight_points_guzzle.client.jira'
            $sprintFieldId: '%env(JIRA_SPRINT_SECTION_FIELD_ID)%'
    
    Invis1ble\ProjectManagement\HotfixPublication\Infrastructure\Domain\Model\TaskTracker\TaskTracker:
        parent: Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Model\TaskTracker\TaskTracker
    
    Invis1ble\ProjectManagement\ReleasePublication\Infrastructure\Domain\Model\TaskTracker\TaskTracker:
        parent: Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Model\TaskTracker\TaskTracker
    
    Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Model\DevelopmentCollaboration\MergeRequest\MergeRequestManagerStack:
        arguments:
            - !tagged_iterator release_management.development_collaboration.merge_request_manager




    GuzzleHttp\Psr7\HttpFactory: ~
    Psr\Http\Message\UriFactoryInterface: '@GuzzleHttp\Psr7\HttpFactory'
    Psr\Http\Message\RequestFactoryInterface: '@GuzzleHttp\Psr7\HttpFactory'
    Psr\Http\Message\StreamFactoryInterface: '@GuzzleHttp\Psr7\HttpFactory'
    
    
    
    
    Invis1ble\ProjectManagement\Shared\Domain\Model\ContinuousIntegration\Project\ProjectResolverInterface: '@Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Model\ContinuousIntegration\Project\ProjectResolver'
    Invis1ble\ProjectManagement\Shared\Domain\Model\TaskTracker\Version\VersionFactoryInterface: '@Invis1ble\ProjectManagement\Shared\Domain\Model\TaskTracker\Version\VersionFactory'
    Invis1ble\ProjectManagement\Shared\Domain\Model\SourceCodeRepository\Branch\BranchFactoryInterface: '@Invis1ble\ProjectManagement\Shared\Domain\Model\SourceCodeRepository\Branch\BranchFactory'
    Invis1ble\ProjectManagement\Shared\Domain\Model\ContinuousIntegration\Job\JobFactoryInterface: '@Invis1ble\ProjectManagement\Shared\Domain\Model\ContinuousIntegration\Job\JobFactory'
    Invis1ble\ProjectManagement\Shared\Domain\Model\ContinuousIntegration\Pipeline\PipelineFactoryInterface: '@Invis1ble\ProjectManagement\Shared\Domain\Model\ContinuousIntegration\Pipeline\PipelineFactory'
    Invis1ble\ProjectManagement\Shared\Domain\Model\SourceCodeRepository\Commit\CommitFactoryInterface: '@Invis1ble\ProjectManagement\Shared\Domain\Model\SourceCodeRepository\Commit\CommitFactory'
    Invis1ble\ProjectManagement\Shared\Domain\Model\SourceCodeRepository\Tag\TagFactoryInterface: '@Invis1ble\ProjectManagement\Shared\Domain\Model\SourceCodeRepository\Tag\TagFactory'
    Invis1ble\ProjectManagement\Shared\Domain\Model\SourceCodeRepository\File\FileFactoryInterface: '@Invis1ble\ProjectManagement\Shared\Domain\Model\SourceCodeRepository\File\FileFactory'
    Invis1ble\ProjectManagement\Shared\Domain\Model\DevelopmentCollaboration\MergeRequest\Details\Status\StatusFactoryInterface: '@Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Model\DevelopmentCollaboration\MergeRequest\Details\Status\StatusFactory'
    Invis1ble\ProjectManagement\Shared\Domain\Model\DevelopmentCollaboration\MergeRequest\Details\DetailsFactoryInterface: '@Invis1ble\ProjectManagement\Shared\Domain\Model\DevelopmentCollaboration\MergeRequest\Details\DetailsFactory'
    Invis1ble\ProjectManagement\Shared\Domain\Model\TaskTracker\Issue\IssueFactoryInterface: '@Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Model\TaskTracker\Issue\IssueFactory'
    Invis1ble\ProjectManagement\HotfixPublication\Domain\Model\HotfixPublicationFactoryInterface: '@Invis1ble\ProjectManagement\HotfixPublication\Infrastructure\Domain\Model\HotfixPublicationFactory'
    Invis1ble\ProjectManagement\HotfixPublication\Domain\Repository\HotfixPublicationRepositoryInterface: '@Invis1ble\ProjectManagement\HotfixPublication\Infrastructure\Domain\Repository\HotfixPublicationRepository'
    Invis1ble\ProjectManagement\HotfixPublication\Domain\Model\TaskTracker\TaskTrackerInterface: '@Invis1ble\ProjectManagement\HotfixPublication\Infrastructure\Domain\Model\TaskTracker\TaskTracker'
    Invis1ble\ProjectManagement\ReleasePublication\Domain\Model\ReleasePublicationFactoryInterface: '@Invis1ble\ProjectManagement\ReleasePublication\Infrastructure\Domain\Model\ReleasePublicationFactory'
    Invis1ble\ProjectManagement\Shared\Domain\Model\DevelopmentCollaboration\MergeRequest\MergeRequestFactoryInterface: '@Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Model\DevelopmentCollaboration\MergeRequest\MergeRequestFactory'
    Invis1ble\ProjectManagement\Shared\Domain\Model\TaskTracker\Sprint\SprintFactoryInterface: '@Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Model\TaskTracker\Sprint\SprintFactory'
    Invis1ble\ProjectManagement\ReleasePublication\Domain\Repository\ReleasePublicationRepositoryInterface: '@Invis1ble\ProjectManagement\ReleasePublication\Infrastructure\Domain\Repository\ReleasePublicationRepository'
    Invis1ble\ProjectManagement\Shared\Domain\Model\TaskTracker\TaskTrackerInterface: '@Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Model\TaskTracker\TaskTracker'
    Invis1ble\ProjectManagement\ReleasePublication\Domain\Model\TaskTracker\TaskTrackerInterface: '@Invis1ble\ProjectManagement\ReleasePublication\Infrastructure\Domain\Model\TaskTracker\TaskTracker'
    Invis1ble\ProjectManagement\Shared\Domain\Model\TaskTracker\Issue\GuiUrlFactoryInterface: '@Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Model\TaskTracker\Issue\GuiUrlFactory'
    Invis1ble\ProjectManagement\Shared\Domain\Model\DevelopmentCollaboration\MergeRequest\MergeRequestManagerInterface: '@Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Model\DevelopmentCollaboration\MergeRequest\MergeRequestManagerStack'
    Invis1ble\ProjectManagement\Shared\Domain\Model\SourceCodeRepository\NewCommit\SetFrontendApplicationBranchNameCommitFactoryInterface: '@Invis1ble\ProjectManagement\Shared\Infrastructure\Domain\Model\SourceCodeRepository\NewCommit\SetFrontendApplicationBranchNameCommitFactory'
    Invis1ble\ProjectManagement\HotfixPublication\Domain\Model\SourceCodeRepository\Tag\MessageFactoryInterface: '@Invis1ble\ProjectManagement\HotfixPublication\Domain\Model\SourceCodeRepository\Tag\MessageFactory'
