# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    saga.state.doctrine.dbal.table_name: 'saga_state'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            bool $debug: '%kernel.debug%'
            Psr\Http\Message\UriInterface $jiraUrl: '@release_management.jira_url'
            Psr\Http\Message\UriInterface $gitlabUrl: '@release_management.gitlab_url'
            ReleaseManagement\Shared\Domain\Model\ContinuousIntegration\Project\ProjectId $backendProjectId: '@release_management.gitlab_project.backend'
            ReleaseManagement\Shared\Domain\Model\ContinuousIntegration\Project\ProjectId $frontendProjectId: '@release_management.gitlab_project.frontend'
            ReleaseManagement\Shared\Domain\Model\SourceCodeRepository\SourceCodeRepositoryInterface $backendSourceCodeRepository: '@release_management.gitlab_backend_client'
            ReleaseManagement\Shared\Domain\Model\SourceCodeRepository\SourceCodeRepositoryInterface $frontendSourceCodeRepository: '@release_management.gitlab_frontend_client'
            ReleaseManagement\Shared\Domain\Model\ContinuousIntegration\ContinuousIntegrationClientInterface $frontendCiClient: '@release_management.gitlab_frontend_client'
            ReleaseManagement\Shared\Domain\Model\ContinuousIntegration\ContinuousIntegrationClientInterface $backendCiClient: '@release_management.gitlab_backend_client'
    _instanceof:
        # services whose classes are instances of CustomInterface will be tagged automatically
        ReleaseManagement\Shared\Domain\Model\DevelopmentCollaboration\MergeRequestManagerInterface:
            tags: ['release_management.development_collaboration.merge_request_manager']

    

    application_layer:
        namespace: ReleaseManagement\
        resource: '../src/*/Application/**/*{Handler,Saga}.php'

    ui_layer:
        namespace: ReleaseManagement\
        resource: '../src/*/Ui/**/*{Command}.php'

    infrastructure_layer:
        namespace: ReleaseManagement\
        resource: '../src/*/Infrastructure/**/*{Factory,Repository,Resolver}.php'
    
    
    
    release_management.jira_url:
        class: Psr\Http\Message\UriInterface
        factory: ['@Psr\Http\Message\UriFactoryInterface', 'createUri']
        arguments: ['%env(JIRA_URL)%']
    
    release_management.gitlab_url:
        class: Psr\Http\Message\UriInterface
        factory: ['@Psr\Http\Message\UriFactoryInterface', 'createUri']
        arguments: ['%env(GITLAB_URL)%']
    
    release_management.gitlab_project.backend:
        class: ReleaseManagement\Shared\Domain\Model\ContinuousIntegration\Project\ProjectId
        arguments:
            $value: '%env(GITLAB_BACKEND_PROJECT_ID)%'

    release_management.gitlab_project.frontend:
        class: ReleaseManagement\Shared\Domain\Model\ContinuousIntegration\Project\ProjectId
        arguments:
            $value: '%env(GITLAB_FRONTEND_PROJECT_ID)%'
    
    ReleaseManagement\Shared\Domain\Model\TaskTracker\Project\Key:
        arguments:
            $value: '%env(JIRA_PROJECT_KEY)%'
    
    ReleaseManagement\Shared\Domain\Model\TaskTracker\Board\BoardId:
        arguments:
            $value: '%env(JIRA_SPRINT_BOARD_ID)%'



    ReleaseManagement\Shared\Infrastructure\Domain\Model\Gitlab\HttpClientFactory:
        arguments:
            $gitlabAccessToken: '%env(GITLAB_ACCESS_TOKEN)%'

    release_management.gitlab_http_client:
        class: GuzzleHttp\Client
        factory: ['@ReleaseManagement\Shared\Infrastructure\Domain\Model\Gitlab\HttpClientFactoryInterface', 'createHttpClient']

    ReleaseManagement\Shared\Infrastructure\Domain\Model\TaskTracker\HttpClientFactory:
        arguments:
            $jiraUsername: '%env(JIRA_USERNAME)%'
            $jiraAccessToken: '%env(JIRA_ACCESS_TOKEN)%'

    release_management.task_tracker.http_client:
        class: GuzzleHttp\Client
        factory: ['@ReleaseManagement\Shared\Infrastructure\Domain\Model\TaskTracker\HttpClientFactoryInterface', 'createHttpClient']
    
    release_management.gitlab_backend_client:
        class: ReleaseManagement\Shared\Infrastructure\Domain\Model\Gitlab\GitlabClient
        arguments:
            $httpClient: '@release_management.gitlab_http_client'
            $projectId: '@release_management.gitlab_project.backend'
    
    release_management.gitlab_frontend_client:
        class: ReleaseManagement\Shared\Infrastructure\Domain\Model\Gitlab\GitlabClient
        arguments:
            $httpClient: '@release_management.gitlab_http_client'
            $projectId: '@release_management.gitlab_project.frontend'
    
    ReleaseManagement\Shared\Infrastructure\Domain\Model\TaskTracker\TaskTracker:
        arguments:
            $httpClient: '@release_management.task_tracker.http_client'
            $sprintFieldId: '%env(JIRA_SPRINT_SECTION_FIELD_ID)%'
    
    ReleaseManagement\ReleasePublication\Infrastructure\Domain\Model\TaskTracker\TaskTracker:
        parent: ReleaseManagement\Shared\Infrastructure\Domain\Model\TaskTracker\TaskTracker
    
    ReleaseManagement\Shared\Infrastructure\Domain\Model\DevelopmentCollaboration\MergeRequestManagerStack:
        arguments:
            - !tagged_iterator release_management.development_collaboration.merge_request_manager



    GuzzleHttp\Psr7\HttpFactory: ~
    Psr\Http\Message\UriFactoryInterface: '@GuzzleHttp\Psr7\HttpFactory'
    Psr\Http\Message\RequestFactoryInterface: '@GuzzleHttp\Psr7\HttpFactory'
    Psr\Http\Message\StreamFactoryInterface: '@GuzzleHttp\Psr7\HttpFactory'
    
    
    ReleaseManagement\Shared\Infrastructure\Domain\Model\Gitlab\HttpClientFactoryInterface: '@ReleaseManagement\Shared\Infrastructure\Domain\Model\Gitlab\HttpClientFactory'
    ReleaseManagement\Shared\Infrastructure\Domain\Model\TaskTracker\HttpClientFactoryInterface: '@ReleaseManagement\Shared\Infrastructure\Domain\Model\TaskTracker\HttpClientFactory'
    ReleaseManagement\Shared\Domain\Model\DevelopmentCollaboration\MergeRequest\Details\Status\StatusFactoryInterface: '@ReleaseManagement\Shared\Infrastructure\Domain\Model\DevelopmentCollaboration\MergeRequest\Details\Status\StatusFactory'
    ReleaseManagement\Shared\Domain\Model\DevelopmentCollaboration\MergeRequest\Details\DetailsFactoryInterface: '@ReleaseManagement\Shared\Infrastructure\Domain\Model\DevelopmentCollaboration\MergeRequest\Details\DetailsFactory'
    ReleaseManagement\Shared\Domain\Model\TaskTracker\Issue\IssueFactoryInterface: '@ReleaseManagement\Shared\Infrastructure\Domain\Model\TaskTracker\Issue\IssueFactory'
    ReleaseManagement\ReleasePublication\Domain\Model\ReleasePublicationFactoryInterface: '@ReleaseManagement\ReleasePublication\Infrastructure\Domain\Model\ReleasePublicationFactory'
    ReleaseManagement\Shared\Domain\Model\DevelopmentCollaboration\MergeRequest\MergeRequestFactoryInterface: '@ReleaseManagement\Shared\Infrastructure\Model\DevelopmentCollaboration\MergeRequestFactory'
    ReleaseManagement\Shared\Domain\Model\TaskTracker\Sprint\SprintFactoryInterface: '@ReleaseManagement\Shared\Infrastructure\Domain\Model\TaskTracker\Sprint\SprintFactory'
    ReleaseManagement\ReleasePublication\Domain\Repository\ReleasePublicationRepositoryInterface: '@ReleaseManagement\ReleasePublication\Infrastructure\Domain\Repository\ReleasePublicationRepository'
    ReleaseManagement\Shared\Domain\Model\TaskTracker\TaskTrackerInterface: '@ReleaseManagement\Shared\Infrastructure\Domain\Model\TaskTracker\TaskTracker'
    ReleaseManagement\ReleasePublication\Domain\Model\TaskTracker\TaskTrackerInterface: '@ReleaseManagement\ReleasePublication\Infrastructure\Domain\Model\TaskTracker\TaskTracker'
    ReleaseManagement\Shared\Domain\Model\TaskTracker\Issue\GuiUrlFactoryInterface: '@ReleaseManagement\Shared\Infrastructure\Domain\Model\TaskTracker\Issue\GuiUrlFactory'
    ReleaseManagement\Shared\Domain\Model\DevelopmentCollaboration\MergeRequestManagerInterface: '@ReleaseManagement\Shared\Infrastructure\Domain\Model\DevelopmentCollaboration\MergeRequestManagerStack'
